### ISSUE TITLE
Add way to fetch custom attributes

### ISSUE THREAD

**Issue by peterjaap** [mobelop/gatsby-source-magento2#1]
I need to fetch custom attributes. Right now I have to manually edit `node_modules/gatsby-source-magento2/nodes/queries/products.js` to add them in the query to be able to fetch them.

**Comment by peterjaap** [comment]
Wait, this can probably be done through fragments. New to this, figuring out as I go.

**Comment by peterjaap** [comment]
Hm not sure how to go about this. Maybe wrap `var _products = _interopRequireDefault(require("./queries/products"));` in a method that extends the result somehow?

**Comment by peterjaap** [comment]
I tried creating a fragment  in a component and importing the component into `queries/product.js` but that's not how that works apparently.

```
  Error: /home/peterjaap/development/workspace/client/project/gatsby/node_modules/gatsby-source-magento2/nodes/queries/products.js:3
  import CustomMagentoAttributes from '../../../../src/components/CustomMagentoAttributes'
  ^^^^^^
  SyntaxError: Unexpected token import

```

**Comment by peterjaap** [comment]
Ok so for now I'm just using `patch-package` to create a patch for the `gatsby-source-magento2` package to add the custom attributes to the query. `</rubberducky>`

**Comment by peterjaap** [comment]
@stansm any idea about this?

**Comment by stansm** [comment]
@peterjaap was going to add an option to pass the custom query for now. will push an updated package today

we are currently building a real project for the client based on a Gatsby frontend. so I'm going to update/improve this package based on that experience

**Comment by stansm** [comment]
@peterjaap pushed an updated version (0.1.3). just pass this new option from now on (I've also updated README):

```
queries: {
                allProductsQuery: `your custom query`
}
```

does this solve your problem?

**Comment by peterjaap** [comment]
@stansm that's perfect, works! Thanks so much :)
