### ISSUE TITLE
Downloading all product images?

### ISSUE THREAD

**Issue by heckchuckman** [mobelop/gatsby-source-magento2#12]
Hello. Thanks for your work on this plug-in. Taking Magento headless with Gatsby is great!

I just installed plug-in and ran the development server for the first time and it attempted to download all product images. Is this correct functionality? If so, is there an option to turn this off?

I'm building custom landing pages with small collections of products, so I don't need all of the images. I'll do filtered category specific queries within components.

Thanks again!

**Comment by stansm** [comment]
Hey @heckchuckman,

You can provide a custom `allProductsQuery` to fetch only the products which you need (you can filter by categories or anything else (some custom attribute maybe). (See README)

Cheers,
Stan

**Comment by heckchuckman** [comment]
Hi @stansm 

Thanks for the quick reply. The issue is that I'm only pulling small batches of products from categories fed from a CMS, and the query is done on the component level. I may need to use a more basic interface like `gatsby-source-graphql`

Thanks again!
