### ISSUE TITLE
product node missing reporter activity start point

### ISSUE THREAD

**Issue by tetuti** [mobelop/gatsby-source-magento2#2]
activity reporter is initialized but never started making the progressbar throw `startTime is undefined`

Compare [products.js:38](https://github.com/mobelop/gatsby-source-magento2/blob/966450c9b85a3d250a3976b632d589adf6b3946b/src/nodes/products.js#L38) to [categories.js:34](https://github.com/mobelop/gatsby-source-magento2/blob/966450c9b85a3d250a3976b632d589adf6b3946b/src/nodes/categories.js#L34) and [:36](https://github.com/mobelop/gatsby-source-magento2/blob/966450c9b85a3d250a3976b632d589adf6b3946b/src/nodes/categories.js#L36)

**Comment by K3vinF** [comment]
I encountered the same issue and can confirm that manually adding `activity.start();` in products.js fixed the issue for me.

**Comment by K3vinF** [comment]
I have made a pull request with this small fix -> https://github.com/mobelop/gatsby-source-magento2/pull/3

**Comment by stansm** [comment]
PR was merged! thank you :)
