### ISSUE TITLE
Wildcards no longer supported

### ISSUE THREAD

**Issue by SimeonUnder2** [mobelop/gatsby-source-magento2#7]
- Fresh Magento install with Sample data
- Fresh Gatsby site with only this plugin installed

Throws an error about:
```
UNHANDLED REJECTION Field "like" is not defined by type FilterEqualTypeInput
```

Which I can remove by modifying the query in nodes/queries/products.js from:
```
  products (
    filter:{
      sku: {
        like:"%"
      }
    }
    pageSize: 10000
  ) {
```

To:
```
  products (
    search: "",
    pageSize: 10000
  ) {
```

The `"%"` wildcard filter seemed to be the problem, and the docs say they're no longer officially supported:
https://devdocs.magento.com/guides/v2.3/graphql/queries/products.html

...but I haven't tested the plugin enough to know if there's any adverse affects to this fix. If it looks fine I can submit a PR.

**Comment by stansm** [comment]
Thank you for reporting!

It required updating some code around images as well. Fix is merged
